from rest_framework import serializers
from .models import Category, Product, ProductImage


class CategorySerializer(serializers.ModelSerializer):
    children = serializers.SerializerMethodField()
    image = serializers.SerializerMethodField()

    class Meta:
        model = Category
        fields = ['id', 'name', 'slug', 'description', 'image', 'parent', 'children', 'is_active', 'created_at']
        read_only_fields = ['slug', 'created_at']

    def get_children(self, obj):
        children = obj.children.filter(is_active=True)
        return CategorySerializer(children, many=True, context=self.context).data

    def get_image(self, obj):
        image = obj.image
        if image:
            url = image.url
            request = self.context.get('request')
            return request.build_absolute_uri(url) if request else url

        # Keep category cards visual even when a category image has not been uploaded.
        product = obj.products.filter(is_active=True).prefetch_related('images').first()
        if product:
            product_image = product.images.filter(is_primary=True).first() or product.images.first()
            if product_image:
                return ProductImageSerializer(product_image, context=self.context).data['url']
        return None


class CategoryMinSerializer(serializers.ModelSerializer):
    class Meta:
        model = Category
        fields = ['id', 'name', 'slug']


class ProductImageSerializer(serializers.ModelSerializer):
    url = serializers.SerializerMethodField()

    class Meta:
        model = ProductImage
        fields = ['id', 'url', 'image_url', 'alt_text', 'is_primary', 'display_order']

    def get_url(self, obj):
        request = self.context.get('request')
        if obj.image_file:
            url = obj.image_file.url
            if request:
                return request.build_absolute_uri(url)
            return url
        return obj.image_url

    def to_representation(self, instance):
        data = super().to_representation(instance)
        if not data.get('image_url') and data.get('url'):
            data['image_url'] = data['url']
        return data


class ProductSerializer(serializers.ModelSerializer):
    images = ProductImageSerializer(many=True, read_only=True)
    category = CategoryMinSerializer(read_only=True)
    category_id = serializers.PrimaryKeyRelatedField(
        queryset=Category.objects.all(),
        source='category',
        write_only=True,
        required=False,
        allow_null=True,
    )
    stock_status = serializers.ReadOnlyField()
    primary_image = serializers.SerializerMethodField()

    class Meta:
        model = Product
        fields = [
            'id', 'name', 'slug', 'description', 'material',
            'price', 'stock_quantity', 'stock_status', 'sku',
            'category', 'category_id', 'is_active',
            'images', 'primary_image', 'created_at', 'updated_at',
        ]
        # slug and sku are auto-generated by model.save() — never require them from the client
        read_only_fields = ['id', 'slug', 'sku', 'stock_status', 'created_at', 'updated_at']

    def get_primary_image(self, obj):
        primary = obj.images.filter(is_primary=True).first()
        if not primary:
            primary = obj.images.first()
        if primary:
            return ProductImageSerializer(primary, context=self.context).data
        return None


class ProductListSerializer(serializers.ModelSerializer):
    """Lighter serializer for list views."""
    stock_status = serializers.ReadOnlyField()
    category = CategoryMinSerializer(read_only=True)
    primary_image = serializers.SerializerMethodField()

    class Meta:
        model = Product
        fields = [
            'id', 'name', 'slug', 'material', 'price', 'stock_quantity',
            'stock_status', 'category', 'primary_image', 'is_active',
        ]

    def get_primary_image(self, obj):
        primary = obj.images.filter(is_primary=True).first()
        if not primary:
            primary = obj.images.first()
        if primary:
            return ProductImageSerializer(primary, context=self.context).data
        return None
