# Generated by Django 5.2.16 on 2026-09-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryzone',
            name='area',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
